### ISSUE TITLE
Cannot connect two images on the same computer

### ISSUE THREAD

**Issue by dupriezt** [dionisiydk/TelePharo#29]
Both images are fresh pharo 8.
I followed the instructions from the readme, that is executing on server image:
```Smalltalk
Metacello new
  baseline: 'TelePharo';
  repository: 'github://pharo-ide/TelePharo';
  load: 'Server'.

TlpRemoteUIManager registerOnPort: 40423
```
And executing on client image:
```Smalltalk
Metacello new
  baseline: 'TelePharo';
  repository: 'github://pharo-ide/TelePharo';
  load: 'Client'.

remotePharo := TlpRemoteIDE connectTo: (TCPAddress ip: #[127 0 0 1] port: 40423)
```

After doing this, the client image freezes. Then after around 10 seconds, there is an error message on the server image: "#findNextHandlerContext was sent to nil".

![image](https://user-images.githubusercontent.com/32486709/67013825-06e70280-f0f4-11e9-8877-aa005a3f69a7.png)

Stack trace:
```
UndefinedObject(Object)>>doesNotUnderstand: #findNextHandlerContext
UndefinedObject>>doesNotUnderstand: #findNextHandlerContext
Context>>nextHandlerContext
OPTimedOutError(Exception)>>pass
BasysCommunicationFailed>>defaultAction
UndefinedObject>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
BasysCommunicationFailed(Exception)>>signal
SeamlessThrowExceptionResult>>returnValue
SeamlessSyncRequestContext>>sendRequest:
SeamlessSyncRequestContext>>sendMessage:
SeamlessObjectReference>>performRemoteMessageWithoutCache:
SeamlessObjectReference>>performRemoteMessage:
SeamlessProxy>>performRemoteMessage:
SeamlessProxyBehaviour>>send:to:
SeamlessProxyBehaviour(GHGhostBehaviour)>>intercept:to:
SeamlessProxy(GHObjectGhost)>>doesNotUnderstand: #asCollectionElement
IdentitySet(Set)>>add:
ObjectTraveler>>skip:
TostMaterialization(TostTransportation)>>skip:
SeamlessObjectReference>>prepareLocalSubstitutionIn:with:
SeamlessObjectTransporter>>prepareLocalSubstitutionOf:with:
TostMaterialization>>readSeamlessSubstitution
SeamlessSubstitutionTostFormat>>readObjectWith:
SeamlessObjectTransporter(TostTransporter)>>readObjectWith:
TostMaterialization>>readNextObject
TostMaterialization>>materializeObject
SeamlessObjectTransporter(TostTransporter)>>receiveObjectFrom:
```

**Comment by dionisiydk** [comment]
Possibly Pharo 8 support requires some changes

чт, 17 окт. 2019 г., 14:37 dupriezt <notifications@github.com>:

**Comment by dionisiydk** [comment]
Right. The log shows it.
The rename of #asSetElement to #asCollectionElement breaks compatibility.
This message should not cause the remote message and should be implemented
by proxies to be managable in the sets

чт, 17 окт. 2019 г., 15:58 Denis Kudriashov <dionisiydk@gmail.com>:

**Comment by oliveiraallex** [comment]
Released Telepharo compatible with Pharo 8:
https://github.com/pharo-ide/TelePharo/releases/tag/v0.4.1

Fixed the issues:
https://github.com/pharo-ide/TelePharo/issues/31
https://github.com/pharo-ide/TelePharo/issues/33
Running ok now.
